---
molecule_exceptions:
  - variation: amazonlinux
    reason: "Not compatible with official repository"

molecule_scenarios:
  - scenario: "default"
    ansible: ["2.10", "2.11", "2.12"]
    platforms:
      - "debian9"
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "ubi8"
      - "fedora34"
      - "fedora35"
