---
# Ansible managed

name: "Ansible Molecule (2.12/default)"

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '7 4 4 * *'

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.2.3
        with:
          command: lint
          scenario: "default"
          ansible: "2.12"

  "default_212":
    needs:
      - linting
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, centos-stream9, ubi8, fedora34, fedora35]  # yamllint disable-line rule:line-length

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.2.3
        with:
          namespace: "ghcr.io/mullholland"
          scenario: "default"
          ansible: "2.12"
          platform: "${{ matrix.platform }}"
